import './globals.css'
import Navigation from '@/components/Navigation.jsx'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  keywords: 'next,react,vercel',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navigation/>
        {children}
        </body>
    </html>
  )
}
